Repository nutanix/papiea, pull requests merged in 2019-05, with the labels that each got.

#109 Add support for Metadata extension validation
  __tests__/database_mongo.test.ts
  __tests__/entity_api.test.ts
  __tests__/metadata_extension.yml
  __tests__/provider_api.test.ts
  __tests__/test_data_factory.ts
  package-lock.json
  package.json
  src/core.ts
  src/databases/spec_db_mongo.ts
  src/databases/status_db_mongo.ts
  src/entity/entity_api_impl.ts
  src/papiea.ts
  src/provider_sdk/typescript_sdk.ts
  start.sh
Labels: review

#117 Set auto reconnection options for mongoDB
  src/databases/mongo.ts
Labels: review

#119 Pass mongo variables to env
  __tests__/database_mongo.test.ts
  src/main.ts
  start.sh
Labels: review

#113 Fix generation of api doc for provider procedures
  src/api_docs/api_docs_generator.ts
Labels: review

#121 Improved test data factory
  __tests__/api_docs.test.ts
  __tests__/entity_api_auth.test.ts
  __tests__/procedures_api.test.ts
  __tests__/provider_api.test.ts
  __tests__/test_data_factory.ts
Labels: review

#120 Improved logging
  package-lock.json
  package.json
  src/main.ts
  start.sh
Labels: review

#122 Remove prompt to fix error with network switch
  __tests__/entity_api_auth.test.ts
  src/auth/oauth2.ts
Labels: review

#123 Api docs handle undefined procedures
  __tests__/api_docs.test.ts
  src/api_docs/api_docs_generator.ts
Labels: in progress, review

#154 s2s keys CRUD in provider API with authz
  papiea-core/package.json
  papiea-core/src/core.ts
  papiea-engine/__tests__/api_docs.test.ts
  papiea-engine/__tests__/auth_user_data.test.ts
  papiea-engine/__tests__/database_mongo.test.ts
  papiea-engine/__tests__/entity_api.test.ts
  papiea-engine/__tests__/entity_api_auth.test.ts
  papiea-engine/__tests__/procedures_api.test.ts
  papiea-engine/__tests__/provider_api.test.ts
  papiea-engine/__tests__/provider_sdk.test.ts
  papiea-engine/package.json
  papiea-engine/src/auth/authn.ts
  papiea-engine/src/auth/authz.ts
  papiea-engine/src/auth/crypto.ts
  papiea-engine/src/auth/oauth2.ts
  papiea-engine/src/databases/mongo.ts
  papiea-engine/src/databases/s2skey_db_interface.ts
  papiea-engine/src/databases/s2skey_db_mongo.ts
  papiea-engine/src/entity/entity_api_impl.ts
  papiea-engine/src/main.ts
  papiea-engine/src/provider/provider_api_impl.ts
  papiea-engine/src/provider/provider_api_interface.ts
  papiea-engine/src/provider/provider_routes.ts
  papiea-sdk/package.json
  papiea-sdk/src/provider_sdk/typescript_sdk.ts
Labels: in review
