Repository nutanix/papiea, pull requests merged in 2020-10, with the labels that each got.

#518 Fix missing build artifacts
  CHANGELOG.md
  README.md
  papiea-backend-utils/package.json
  papiea-client/package.json
  papiea-core/package.json
  papiea-engine/package.json
  papiea-engine/tsconfig.json
  papiea-sdk/typescript/package.json
  upgrade-versions.sh
Labels: backlog, in progress

#520 Add new options to customize timeouts
  README.md
  papiea-engine/src/diff_resolver_main.ts
  papiea-engine/src/utils/arg_parser.ts
Labels: backlog, in progress

#516 Add IntentWatcher API
  papiea-client/src/entity_client.ts
  papiea-sdk/python/e2e_tests/__init__.py
  papiea-sdk/python/e2e_tests/kinds/bucket_kind.yml
  papiea-sdk/python/e2e_tests/kinds/object_kind.yml
  papiea-sdk/python/e2e_tests/procedure_handlers.py
  papiea-sdk/python/e2e_tests/provider_setup.py
  papiea-sdk/python/e2e_tests/requirements.txt
  papiea-sdk/python/e2e_tests/sdk_test.py
  papiea-sdk/python/e2e_tests/security/metadata_extension.yml
  papiea-sdk/python/e2e_tests/utils.py
  papiea-sdk/python/papiea/client.py
  papiea-sdk/python/papiea/core.py
  papiea-sdk/python/papiea/python_sdk.py
  papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk_interface.ts
Labels: in progress

#495 Add python sdk tests
  .circleci/Dockerfile
  .circleci/config.yml
  Makefile
  papiea-engine/Dockerfile
  papiea-engine/src/errors/papiea_error_impl.ts
  papiea-sdk/python/e2e_tests/procedure_handlers.py
  papiea-sdk/python/e2e_tests/provider_setup.py
  papiea-sdk/python/e2e_tests/sdk_test.py
  papiea-sdk/python/e2e_tests/utils.py
  papiea-sdk/python/papiea/api.py
  papiea-sdk/python/papiea/client.py
  papiea-sdk/python/papiea/core.py
  papiea-sdk/python/papiea/python_sdk_context.py
  papiea-sdk/python/papiea/python_sdk_exceptions.py
  papiea-sdk/python/tests/__init__.py
  papiea-sdk/python/tests/requirements.txt
  papiea-sdk/python/tests/sdk_test.py
  papiea-sdk/python/tests/test_data/location_kind_test_data.yml
  papiea-sdk/python/tests/test_data/location_kind_test_data_array.yml
  papiea-sdk/python/tests/test_data/location_kind_test_data_array_sfs.yml
  papiea-sdk/python/tests/test_data/location_kind_test_data_callback.yml
  papiea-sdk/python/tests/test_data/procedure_move_input.yml
  papiea-sdk/python/tests/test_data/procedure_move_output.yml
  papiea-sdk/python/tests/test_data/provider_model_example.txt
Labels: waiting_for_merge
