Repository nutanix/papiea, pull requests merged in 2020-12, with the labels that each got.

#555 Separated null value fields and unset in status db
  papiea-backend-utils/src/dotnotation.ts
  papiea-engine/__tests__/provider_tests/provider_api.test.ts
  papiea-engine/src/databases/status_db_mongo.ts
  papiea-engine/src/provider/provider_api_impl.ts
  papiea-engine/src/provider/provider_api_interface.ts
Labels: in review

#546 Added module to remove status-only fields from entity status
  papiea-client/__tests__/filter.test.ts
  papiea-client/__tests__/update.test.ts
  papiea-core/src/core.ts
  papiea-engine/src/intentful_core/differ_impl.ts
  papiea-engine/src/intentful_engine/diff_resolver.ts
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk_exceptions.ts
Labels: in review

#550 Custom entity constructors implementation
  papiea-backend-utils/package.json
  papiea-backend-utils/yarn.lock
  papiea-client/package.json
  papiea-client/src/entity_client.ts
  papiea-client/src/location_client_example.ts
  papiea-client/yarn.lock
  papiea-core/package.json
  papiea-core/src/core.ts
  papiea-core/yarn.lock
  papiea-engine/__benchmarks__/package.json
  papiea-engine/__benchmarks__/yarn.lock
  papiea-engine/__tests__/auth_tests/entity_api_auth.test.ts
  papiea-engine/__tests__/entity_tests/sorting.test.ts
  papiea-engine/__tests__/provider_tests/provider_api.test.ts
  papiea-engine/__tests__/watcher_tests/intent_watcher.test.ts
  papiea-engine/package.json
  papiea-engine/src/api_docs/api_docs_generator.ts
  papiea-engine/src/auth/authz.ts
  papiea-engine/src/diff_resolver_main.ts
  papiea-engine/src/entity/entity_api_impl.ts
  papiea-engine/src/entity/entity_api_interface.ts
  papiea-engine/src/entity/entity_routes.ts
  papiea-engine/src/errors/on_action_error.ts
  papiea-engine/src/intentful_core/entity_creation_strategies/basic_entity_creation_strategy.ts
  papiea-engine/src/intentful_core/entity_creation_strategies/constructor_entity_creation_strategy.ts
  papiea-engine/src/intentful_core/entity_creation_strategies/entity_creation_strategy_interface.ts
  papiea-engine/src/intentful_core/intentful_context.ts
  papiea-engine/src/intentful_core/intentful_strategies/basic_intentful_strategy.ts
  papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
  papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
  papiea-engine/src/intentful_core/intentful_strategies/spec_only_intentful_strategy.ts
  papiea-engine/src/main.ts
  papiea-engine/src/papiea.ts
  papiea-engine/src/provider/provider_api_impl.ts
  papiea-engine/src/provider/provider_api_interface.ts
  papiea-engine/yarn.lock
  papiea-sdk/python/e2e_tests/procedure_handlers.py
  papiea-sdk/python/e2e_tests/provider_setup.py
  papiea-sdk/python/e2e_tests/sdk_test.py
  papiea-sdk/python/e2e_tests/utils.py
  papiea-sdk/python/papiea/api.py
  papiea-sdk/python/papiea/client.py
  papiea-sdk/python/papiea/core.py
  papiea-sdk/python/papiea/python_sdk.py
  papiea-sdk/python/papiea/python_sdk_exceptions.py
  papiea-sdk/python/tests/sdk_test.py
  papiea-sdk/python/tests/test_data/location_kind_test_data.yml
  papiea-sdk/python/tests/test_data/location_kind_test_data_array.yml
  papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
  papiea-sdk/typescript/package.json
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk_interface.ts
  papiea-sdk/typescript/yarn.lock
Labels: backlog, enhancement, in progress

#564 Added deprecate info for the replace_status sdk method and relavant tests
  papiea-backend-utils/src/logging.ts
  papiea-engine/src/databases/status_db_mongo.ts
  papiea-sdk/python/e2e_tests/procedure_handlers.py
  papiea-sdk/python/e2e_tests/requirements.txt
  papiea-sdk/python/papiea/python_sdk_context.py
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
Labels: in progress

#569 Added validation check to not allow required status-only fields in schema
  papiea-engine/src/validator/index.ts
  papiea-sdk/python/e2e_tests/procedure_handlers.py
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Labels: in progress
