Repository nutanix/papiea, pull requests merged in 2021-03, with the labels that each got.

#645 Remove undefined and null fields from the differ input
  papiea-core/src/core.ts
  papiea-engine/__tests__/intentful_engine_tests/differ.test.ts
  papiea-engine/__tests__/intentful_engine_tests/sfs_compiler.test.ts
  papiea-engine/src/intentful_core/differ_impl.ts
  papiea-engine/src/intentful_core/sfs_compiler.ts
  papiea-engine/src/intentful_engine/diff_resolver.ts
  papiea-engine/src/intentful_engine/intent_resolver.ts
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Labels: review

#649 Modified logic for the sanitizer functions in sfs compiler
  papiea-engine/src/intentful_core/sfs_compiler.ts
Labels: in progress

#653 Fix custom field bugs & added metadata extension adjustment
  papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
  papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
Labels: bug

#651 Added validator check for untyped object not marked as status-only
  papiea-engine/src/validator/index.ts
  papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Labels: review
